version: "3.7"

services:
    alliHunter:
        image: devoverlord93/monocle:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli processor --scope=alliHunter
        container_name: alliHunter
        hostname: alliHunter
        env_file:
            - .env-docker
    alliUpdater:
        image: devoverlord93/monocle:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli processor --scope=alliUpdater --workers=2 --records=100
        container_name: alliUpdater
        hostname: alliUpdater
        env_file:
            - .env-docker
    charUpdater:
        image: devoverlord93/monocle:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli processor --scope=charUpdater --workers=50 --records=1000
        container_name: charUpdater
        hostname: charUpdater
        env_file:
            - .env-docker
    charHunter:
        image: devoverlord93/monocle:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli processor --scope=charHunter --records=10
        container_name: charHunter
        hostname: charHunter
        env_file:
            - .env-docker
    corpHunter:
        image: devoverlord93/monocle:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli processor --scope=corpHunter
        container_name: corpHunter
        hostname: corpHunter
        env_file:
            - .env-docker
    corpUpdater:
        image: devoverlord93/monocle:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli processor --scope=corpUpdater
        container_name: corpUpdater
        hostname: corpUpdater
        env_file:
            - .env-docker
    cron:
        image: devoverlord93/monocle:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli cron
        container_name: cron
        hostname: cron
        env_file:
            - .env-docker
    api:
        image: devoverlord93/monocle:${DOCKER_VERSION}
        network_mode: "host"
        restart: on-failure
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli api
        container_name: api
        hostname: api
        env_file:
            - .env-docker
        ports:
            - "8080:8080"
