version: "3.7"

services:
    image:
        image: core
        build:
            context: .
            dockerfile: Dockerfile
    updater_char:
        image: core
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli processor --scope=charUpdater --workers=25 --records=250
        network_mode: "host"
        container_name: updater_char
        env_file:
            - ./cmd/.env-docker
    hunter_char:
        image: core
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli processor --scope=charHunter --records=10
        network_mode: "host"
        container_name: hunter_char
        env_file:
            - ./cmd/.env-docker
    hunter_corp:
        image: core
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "50m"
        command: ./cli processor --scope=corpHunter
        network_mode: "host"
        container_name: hunter_corp
        env_file:
            - ./cmd/.env-docker
