// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"fmt"
	"io"
	"strconv"
)

type Sort string

const (
	SortAsc  Sort = "ASC"
	SortDesc Sort = "DESC"
)

var AllSort = []Sort{
	SortAsc,
	SortDesc,
}

func (e Sort) IsValid() bool {
	switch e {
	case SortAsc, SortDesc:
		return true
	}
	return false
}

func (e Sort) String() string {
	return string(e)
}

func (e *Sort) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Sort(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Sort", str)
	}
	return nil
}

func (e Sort) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortColumns string

const (
	SortColumnsID       SortColumns = "ID"
	SortColumnsBirthday SortColumns = "BIRTHDAY"
	SortColumnsExpires  SortColumns = "EXPIRES"
)

var AllSortColumns = []SortColumns{
	SortColumnsID,
	SortColumnsBirthday,
	SortColumnsExpires,
}

func (e SortColumns) IsValid() bool {
	switch e {
	case SortColumnsID, SortColumnsBirthday, SortColumnsExpires:
		return true
	}
	return false
}

func (e SortColumns) String() string {
	return string(e)
}

func (e *SortColumns) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortColumns(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortColumns", str)
	}
	return nil
}

func (e SortColumns) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
