// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package boiler

var TableNames = struct {
	Alliances         string
	Characters        string
	CorporationDeltas string
	Corporations      string
}{
	Alliances:         "alliances",
	Characters:        "characters",
	CorporationDeltas: "corporation_deltas",
	Corporations:      "corporations",
}
