name: "DockerBuildAndDeploy"
on:
  release:
    types: [published]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Publish To Docker
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: devoverlord93/monocle
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile
        tag_names: true
