// Code generated by SQLBoiler 3.5.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Alliances                   string
	CharacterCorporationHistory string
	Characters                  string
	CorporationAllianceHistory  string
	CorporationDeltas           string
	Corporations                string
	Etags                       string
	KV                          string
}{
	Alliances:                   "alliances",
	CharacterCorporationHistory: "character_corporation_history",
	Characters:                  "characters",
	CorporationAllianceHistory:  "corporation_alliance_history",
	CorporationDeltas:           "corporation_deltas",
	Corporations:                "corporations",
	Etags:                       "etags",
	KV:                          "kv",
}
